manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
  - name: zmk
    revision: main
  - name: zmk-config
    path: config
  - name: zmk-keyboard-lagom65
    path: modules/lagom65
    url: https://github.com/jetjetjet/zmk-keyboard-lagom65